receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  otlphttp/vercel-traces:
    traces_endpoint: https://stock-observability-ui.vercel.app/api/v1/otel
    encoding: json
    headers:
      x-otel-secret: "${OTEL_INGEST_SECRET}"
    retry_on_failure:
      enabled: true
      max_elapsed_time: 300s
  otlphttp/vercel-metrics:
    metrics_endpoint: https://stock-observability-ui.vercel.app/api/v1/otel-metrics
    encoding: json
    headers:
      x-otel-secret: "${OTEL_INGEST_SECRET}"
    retry_on_failure:
      enabled: true
      max_elapsed_time: 300s
  otlphttp/vercel-logs:
    logs_endpoint: https://stock-observability-ui.vercel.app/api/v1/otel-logs
    encoding: json
    headers:
      x-otel-secret: "${OTEL_INGEST_SECRET}"
    retry_on_failure:
      enabled: true
      max_elapsed_time: 300s
  logging:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlphttp/vercel-traces, logging]
    metrics:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlphttp/vercel-metrics, logging]
    logs:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlphttp/vercel-logs, logging]
